version: "3.9"

services:
  db:
    image: postgres:16
    container_name: devoops_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build: ./app
    container_name: devoops_api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
