FROM python:3.11-slim

# Define o diretório de trabalho
WORKDIR /app

# Instala dependências necessárias
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    python3-dev \
    pkg-config \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Copia dependências Python
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copia toda a aplicação
COPY . .

# Garante permissão de execução ao script
RUN chmod +x /app/wait-for-db.sh

# Expõe a porta da aplicação
EXPOSE 8000

# Comando para esperar o banco e iniciar o servidor
CMD ["./wait-for-db.sh", "db", "uvicorn", "main:app", "--host=0.0.0.0", "--port=8000"]
